//APP
export const PICK_CATEGORY = "PICK_CATEGORY";
export const PICK_SUBJECT = "PICK_SUBJECT";

//CATEGORIES
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

//SUBJECTS
export const SET_SUBJECTS = "SET_SUBJECTS";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";
export const REMOVE_SUBJECTS_FOR_CATEGORY = "REMOVE_SUBJECTS_FOR_CATEGORY";

//RECORDS
export const SET_RECORDS = "SET_RECORDS";
export const ADD_RECORD = "ADD_RECORD";
export const EDIT_RECORD = "EDIT_RECORD";
export const REMOVE_RECORD = "REMOVE_RECORD";
export const REMOVE_RECORDS_FOR_CATEGORY = "REMOVE_RECORDS_FOR_CATEGORY";
export const REMOVE_RECORDS_FOR_SUBJECT = "REMOVE_RECORDS_FOR_SUBJECT";

//SETTINGS
export const SET_SETTINGS = "SET_SETTINGS";
export const SET_DEFAULT_GOAL_CHART_TYPE = "SET_DEFAULT_GOAL_CHART_TYPE";
export const SET_DEFAULT_TIME_CHART_TYPE = "SET_DEFAULT_TIME_CHART_TYPE";
export const SET_GOALS = "SET_GOALS";
