//CATEGORIES
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ADD_CATEGORY = "ADD_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const REMOVE_CATEGORY = "REMOVE_CATEGORY";

//SUBJECTS
export const SET_SUBJECTS = "SET_SUBJECTS";
export const ADD_SUBJECT = "ADD_SUBJECT";
export const EDIT_SUBJECT = "EDIT_SUBJECT";
export const REMOVE_SUBJECT = "REMOVE_SUBJECT";

//APP
export const PICK_CATEGORY = "PICK_CATEGORY";
